### ISSUE TITLE
SVG fill-opacity attribute not working when fill attribute is in rgb/rgba/hsl

### ISSUE THREAD

**Issue by mhadar** [dompdf/php-svg-lib#109]
When you have fill set in rgb format, the fill-opacity is then not respected.

This produce opaque image, but it should be 50% transparent:
`<svg width="19" height="18" viewBox="0 0 19 18" xmlns="http://www.w3.org/2000/svg">
<path d="M9.5 0L18.5933 18H0.406734L9.5 0Z" fill="rgb(0, 154, 203)" fill-opacity="0.5"/>
</svg>`

![php-svg-triangle-opaque](https://github.com/dompdf/php-svg-lib/assets/29734562/627aaf8a-01e0-4759-92d1-8c1fb525a439)

When we have fill set in hex color, then the image is correctly semitransparent:
`<svg width="19" height="18" viewBox="0 0 19 18" xmlns="http://www.w3.org/2000/svg">
<path d="M9.5 0L18.5933 18H0.406734L9.5 0Z" fill="#009ACB" fill-opacity="0.5"/>
</svg>`

![php-svg-triangle-transparent](https://github.com/dompdf/php-svg-lib/assets/29734562/e91cae1a-e9a7-4fea-936b-3121cf8fd00d)

Problem is this condition, in file src/Svg/Style.php on line 165:
`                        if ($value !== null && $value[3] !== 1 && array_key_exists("{$from}-opacity", $style_map) === true) {`
because $value[3] is number, when color is in hex format, but string when color is in rgb/rgba/hsl format. After I changed to this, the svg is correct:
`                        if ($value !== null && $value[3] != 1 && array_key_exists("{$from}-opacity", $style_map) === true) {`

**Comment by bsweeney** [comment]
The issue appears to be that we were treating the parsed color value inconsistently. I modified the logic so that the parsed components are now consistently returned and handled as decimal values.
