### ISSUE TITLE
ErrorException: Undefined property: Svg\Style::$href

### ISSUE THREAD

**Issue by rhorbas** [dompdf/php-svg-lib#114]
I have an SVG image embedded in a PDF, which now throws an exception after updating to PHP 8.3 and Laravel 10.

File: 
src/Svg/Style.php: 146

```php
if (
    \array_key_exists("font-family", $styles)
    && (
        \strtolower(\substr($this->href, 0, 7)) === "phar://"
        || ($this->document->allowExternalReferences === false && \strtolower(\substr($this->href, 0, 5)) !== "data:")
    )
) {
    unset($style["font-family"]);
}
```

(After commenting out this block, the PDF is working again.)

**Comment by bsweeney** [comment]
I was just reviewing this code yesterday and realized that it's ... not correct. Working on a fix and should have it out soon.

**Comment by pereira-pedro** [comment]
Hello,

Is safe to remove this (src/Svg/Style.php:146) until a fix is published?

`   if (
                    \array_key_exists("font-family", $styles)
                    && (
                        \strtolower(\substr($this->href, 0, 7)) === "phar://"
                        || ($this->document->allowExternalReferences === false && \strtolower(\substr($this->href, 0, 5)) !== "data:")
                    )
                ) {
                    unset($styles["font-family"]);
                }`

**Comment by bsweeney** [comment]
I just added the change to master branch. If you have a moment to test and it looks good I'll go ahead and publish the next release.

**Comment by pereira-pedro** [comment]
I'm sorry but found another issue:

`Message: 'Undefined variable $from', Trace: '#0 /app/sources/vendor/phenx/php-svg-lib/src/Svg/Tag/Image.php(61): `

**Comment by bsweeney** [comment]
Don't be sorry. _I'm_ the one who should be sorry, that was just sloppy. Should be fixed now.

**Comment by pereira-pedro** [comment]
I'm sorry because you're the one who is volunteering to do this work. I'm just a consumer. :D

Anyways. It works! 

Thank you!
