### ISSUE TITLE
Paths in SVG without a fill specified are not visible

### ISSUE THREAD

**Issue by usb248** [dompdf/php-svg-lib#24]
Hi,

 The owner of dompdf (which use your lib) suppose that your new release is broken : [link](https://github.com/dompdf/dompdf/issues/1612)

Can you tell me more ?

**Comment by landsman** [comment]
It's interesting for me too

**Comment by pfbernardo** [comment]
Hi,

Same here. 
With Dompdf 0.8.1 and 0.8.2 using version 0.3.* stopped working

**Comment by usb248** [comment]
Any fix... project is died

**Comment by devbranch-nikita** [comment]
For the next who will seek, here's workaround [https://github.com/dompdf/dompdf/issues/1612#issuecomment-499258250](https://github.com/dompdf/dompdf/issues/1612#issuecomment-499258250)

Many thanks to @vielhuber.

Copy of the comment with the solution (just in case)
> For anybody struggling with this:
> 
> Replace
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 79.02 55.93">
> ```
> 
> with
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 79.02 55.93" fill="#000000">
> ```
> 
> and everything works!
> 
> Here is a command line batch script that does that for you:
> 
> ```
> find . -type f -name "*.svg" -print0 | xargs -0 sed -i '' -e 's/<svg xmlns/<svg fill="#000000" xmlns/g'
> ```

**Comment by SiamShaeed** [comment]
Hi. did you have a solution? I have the same problem.
