### ISSUE TITLE
Incorrect assignment in if statement

### ISSUE THREAD

**Issue by mbomb007** [dompdf/php-svg-lib#56]
### Version 0.3.4

I found the following using a code scan:

```php
if ($stroke = $style->stroke && is_array($style->stroke)) {
```

This is in SurfacePDFLib.php

This is equivalent to the following because assignment happens after the Boolean `&&`.
```php
if ($stroke = ($style->stroke && is_array($style->stroke))) {
```

I just want to make sure that this isn't a problem in some way, because this mistake is common. If wrong, it would be fixed by

```php
if (($stroke = $style->stroke) && is_array($style->stroke)) {
```

or by using `and` instead of `&&`.

Another occurrence in the same file:

```php
if ($fill = $style->fill && is_array($style->fill)) {
```

Previously posted issue: https://github.com/dompdf/dompdf/issues/2113

**Comment by bsweeney** [comment]
Probably a mistake. The logic in the other two adapters is slightly different.
