### ISSUE TITLE
Move to dompdf organization

### ISSUE THREAD

**Issue by PowerKiKi** [dompdf/php-svg-lib#72]
@PhenX, a while ago you agreed to move this project under the https://github.com/dompdf organization. This would help have more contributors and ensure the project will not die due to lack of contributions. And will still keep all the access and privileges you have currently.

You can do that by going to https://github.com/PhenX/php-svg-lib/settings and click on the `Transfer` button:

![image](https://user-images.githubusercontent.com/72603/137669042-3dea892a-33c5-458b-bec6-1950641e176d.png)

Or, alternatively, could you please add me as admin so that I can migrate from Travis to GitHub Actions and thus have working CI again ?

**Comment by PhenX** [comment]
Hello, sure I'm going to add you as admin, but before moving to the dompdf I'll ask Brian if he's OK with this :)

**Comment by PowerKiKi** [comment]
Thank you for considering this. It is indeed a good idea to ask the opinion of @bsweeney, as he might be impacted by this.

On the other hand, it does not necessarily means more work for him. Contributors should follow the move, and ideally Brian involvement should be the same as it is now.

**Comment by PhenX** [comment]
@PowerKiKi @bsweeney done :)
