### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by mussbach** [dompdf/php-svg-lib#85]
I wonder, which license apply to this library, as the `composer.json` states that it would be `LGPL-3.0`, but your `LICENSE` file is a GPL 3.0. 

Did you perhaps accidentally forget to include a `LICENSE LESSER` file or the like?

**Comment by ssddanbrown** [comment]
Just voicing that I would also appreciate this to be confirmed.
I typically use `composer licenses` to check my dependency tree license (which reflects LGPL-3.0).

Got quite scared when I saw this and the GPL3 license in the repo, thinking I may have to remove my use of DOMPDF (Or re-license my project), until I saw each file has a specific `@license GNU LGPLv3+` header which gives some confidence that `LGPLv3` is the intention, but would be nice to have that confirmed. 
GitHub detects based upon the license file and also is reflecting `GPL-3.0 license` in the project details.

**Comment by bsweeney** [comment]
So, yeah. It looks like when the COPYING file was introduced both the LGPL and GPL version were put in the library. Looks like I thought they were duplicates without realizing that they were two different license files. Considering the file headers and history the intention was for the license to be LGPL. I'll update the file to match the headers, i.e. LGPL 3.

Note that the other Dompdf projects are currently using LGPL 2.1.

**Comment by ssddanbrown** [comment]
Cool, Thank you very much for the confirmation!
